### PR TITLE
Updated version to 2.2.0

### PR DESCRIPTION
**Pull request by terhardt**
This is the most current version on pypi

### CODE REVIEW

**Comment by ericdill** [comment]
Awesome, thanks! Can you update the md5 too?

**Comment by terhardt** [comment]
Sorry, I've missed that. I can squash the two commits and send a new pull request if you want

**Comment by ericdill** [comment]
No worries. There is a lot to keep track of :grinning: No need to squash commits. I'll revisit this once CI's have finished

**Comment by terhardt** [comment]
Please do not merge this yet, as an error has popped up in this release, see: dfm/emcee#186 and dfm/emcee#187

 Guess its best to stick to 2.1.0 for the time being.

**Comment by dfm** [comment]
Thanks to @terhardt's pull request, this is fixed and I've pushed the 2.2.1 bugfix release. Sorry about this!

**Comment by terhardt** [comment]
I've update the recipe to 2.2.1

**Comment by ericdill** [comment]
Thanks @terhardt!

**Pull request merged**
