### PR TITLE
MNT: Feedstock update

### PR DESCRIPTION
**Pull request by terhardt**
This includes changes from #2.

To make the current version of the feedstock work we need to add 'setuptools' as a build dependency.

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please bump the build number too?

**Comment by terhardt** [comment]
Sure thing. I can also squash my commits into one if that needed.

**Comment by jakirkham** [comment]
Please [re-render](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) with `conda-smithy` version `1.3.3`. That should fix the AppVeyor failure.

**Comment by jakirkham** [comment]
Squashing is unnecessary IMHO.

**Comment by jakirkham** [comment]
Thanks @terhardt .

**Pull request merged**
