### PR TITLE
Adding builds on python 3.6

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by ericdill** [comment]
Hi @bsipocz. Thanks for the pull-request. I'd like to suggest that you use the automated feedstock management tool called `conda-smithy` which, among other things, will now add the Python 3.6 support to the CI services. It's quite easy to use and means that you don't need to manually edit the CI files.

1. Install it: `conda install conda-smithy` (The current version is 2.1.1)
2. "Rerender" the feedstock with `conda-smithy rerender`. e.g.:

```bash
$ conda-smithy rerender
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Fetching package metadata ...........
Fetching package metadata ...........
Fetching package metadata .............
Fetching package metadata .............

Re-rendered with conda-smithy 2.1.1.

You can commit the changes with:

    git commit -m "MNT: Re-rendered with conda-smithy 2.1.1"

These changes need to be pushed to github!
```

3. Commit the changes with the above message and push it up to this branch.

**Comment by ericdill** [comment]
Err I did not write that out properly. There is no positional argument for the path to the feedstock. You need to be in the feedstock directory when you run `conda-smithy rerender`. I've edited the original post to reflect this.

**Comment by bsipocz** [comment]
Thanks, I wasn't aware of this tool.

**Comment by bsipocz** [comment]
Well, I run into ``KeyError`` issues with ``conda-smithy``, but don't have time atm to figure out how to fix it. Anyone please feel free to push directly to this branch, or just close the PR. Alternatively I'll try to come back to this at some point.

**Pull request closed without merging**
